name: Build test Docker

on:
  push:
    branches: [ master ]

jobs:

  build-apt-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if Dockers has changed
        uses: marceloprado/has-changed-path@v1
        id: has-changed
        with:
          paths: dockers
      - name: Build Apt Shellspec test Docker and Publish to GitHub Docker Registry
        if: steps.has-changed.outputs.changed == 'true'
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: docker.pkg.github.com/${{ github.repository }}/shellspec
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ./dockers/apt/Dockerfile
          tags: "apt"

  build-apk-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if Dockers has changed
        uses: marceloprado/has-changed-path@v1
        id: has-changed
        with:
          paths: dockers
      - name: Build Apk Shellspec test Docker and Publish to GitHub Docker Registry
        if: steps.has-changed.outputs.changed == 'true'
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: docker.pkg.github.com/${{ github.repository }}/shellspec
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ./dockers/apk/Dockerfile
          tags: "apk"

  build-yum-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if Dockers has changed
        uses: marceloprado/has-changed-path@v1
        id: has-changed
        with:
          paths: dockers
      - name: Build Yum Shellspec test Docker and Publish to GitHub Docker Registry
        if: steps.has-changed.outputs.changed == 'true'
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: docker.pkg.github.com/${{ github.repository }}/shellspec
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ./dockers/yum/Dockerfile
          tags: "yum"

  build-pacman-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if Dockers has changed
        uses: marceloprado/has-changed-path@v1
        id: has-changed
        with:
          paths: dockers
      - name: Build Pacman Shellspec test Docker and Publish to GitHub Docker Registry
        if: steps.has-changed.outputs.changed == 'true'
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: docker.pkg.github.com/${{ github.repository }}/shellspec
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ./dockers/pacman/Dockerfile
          tags: "pacman"

  build-dnf-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if Dockers has changed
        uses: marceloprado/has-changed-path@v1
        id: has-changed
        with:
          paths: dockers
      - name: Build DNF Shellspec test Docker and Publish to GitHub Docker Registry
        if: steps.has-changed.outputs.changed == 'true'
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: docker.pkg.github.com/${{ github.repository }}/shellspec
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: ./dockers/dnf/Dockerfile
          tags: "dnf"
